export const BINANCE_DELISTED_SYMBOLS = new Set([
  "1000WHYUSDT", "1000XUSDT", "42USDT", "AGIXUSDT", "AI16ZUSDT", "ALPACAUSDT", "ALPHAUSDT",
  "AMBUSDT", "BADGERUSDT", "BAKEUSDT", "BALUSDT", "BDXNUSDT", "BIDUSDT", "BLZUSDT", "BNXUSDT",
  "BONDUSDT", "BSWUSDT", "BTCSTUSDT", "CHESSUSDT", "COMBOUSDT", "COMMONUSDT", "CUDISUSDT",
  "DARUSDT", "DEFIUSDT", "DFUSDT", "DGBUSDT", "DMCUSDT", "EOSUSDT", "EPTUSDT", "FISUSDT",
  "FLMUSDT", "FRONTUSDT", "FTMUSDT", "FTTUSDT", "FXSUSDT", "GAIBUSDT", "GHSTUSDT", "GLMRUSDT",
  "HIFIUSDT", "IDEXUSDT", "KDAUSDT", "KEYUSDT", "KLAYUSDT", "LEVERUSDT", "LINAUSDT", "LOKAUSDT",
  "LOOMUSDT", "MATICUSDT", "MDTUSDT", "MEMEFIUSDT", "MILKUSDT", "MKRUSDT", "MYROUSDT",
  "NEIROETHUSDT", "NKNUSDT", "NULSUSDT", "OBOLUSDT", "OCEANUSDT", "OMGUSDT", "OMNIUSDT",
  "OMUSDT", "ORBSUSDT", "PERPUSDT", "PONKEUSDT", "PORT3USDT", "QUICKUSDT", "RADUSDT",
  "RAYUSDT", "REEFUSDT", "REIUSDT", "RENUSDT", "RVVUSDT", "SCUSDT", "SKATEUSDT", "SLERFUSDT",
  "SNTUSDT", "STMXUSDT", "STPTUSDT", "STRAXUSDT", "SWELLUSDT", "SXPUSDT", "TANSSIUSDT",
  "TOKENUSDT", "TROYUSDT", "UNFIUSDT", "UXLINKUSDT", "VFYUSDT", "VIDTUSDT", "VOXELUSDT",
  "WAVESUSDT", "XCNUSDT", "XEMUSDT", "YALAUSDT", "ZRCUSDT",
  "A2ZUSDT", "FORTHUSDT", "HOOKUSDT", "LRCUSDT", "NTRNUSDT", "RDNTUSDT",
]);

const BINANCE_MAJORS = ["BTC", "ETH", "BNB", "SOL", "HYPE", "LINK", "XRP", "TRX", "ADA", "WLFI", "AAVE", "SKY", "DOGE", "BCH"];
const BINANCE_METALS = ["XAU", "XAG", "XPT", "XPD", "COPPER", "PAXG", "XAUT"];
const BINANCE_ENERGY = ["CL", "BZ", "NATGAS"];
const BINANCE_STOCKS = [
  "TSLA", "MSTR", "AMZN", "AAPL", "NVDA", "EWY", "EWJ", "QQQ", "SPY", "META", "GOOGL", "MSFT", "NFLX", "AMD", "INTC", "COIN",
  "BABA", "TSM", "JPM", "V", "MA", "DIS", "PYPL", "UBER", "ABNB", "SOFI", "PLTR", "HOOD", "RIVN", "LCID", "NIO",
  "XOM", "CRCL", "PFE", "JNJ", "UNH", "HD", "WMT", "COST", "TGT", "NKE", "SBUX", "MCD", "KO", "PEP",
  "QQQX", "TQQQ", "SPXL", "SOXL", "TNA", "UVXY", "VIX", "TLT", "IEF", "LQD", "HYG", "EMB", "PAYP",
  "MSTRX", "COINX", "NVDAX", "AAPLX", "GOOGLX", "ORCLX", "TQQQX", "PLTRX", "METAX", "AMZNX", "HOODX",
];

export function getBinanceAssetCategory(symbol: string): string {
  const base = symbol.replace(/USDT$/i, "").toUpperCase();
  if (BINANCE_MAJORS.includes(base)) return "Majors";
  if (BINANCE_METALS.includes(base)) return "Metals";
  if (BINANCE_ENERGY.includes(base)) return "Energy";
  if (BINANCE_STOCKS.includes(base)) return "Stocks";
  return "Other Crypto";
}
